testing_mode = true #not required for bmac
payment_provider = "bmac" #stripe if using strip, bmac for buy me a coffee
client_id = "17...." #OAuth client Google API
client_secret = "GO...." #google Oauth 2.0 client secret
redirect_url_test = 'http://localhost.com:8501' #google api redirect url(replace with actual url in case of deployment)
bmac_api_key = "......." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/app/membership/levels" #only needed if using buy me a coffee